#ifndef CLEANINGSCHEDULEGENERATOR.CORE_GLOBAL_H
#define CLEANINGSCHEDULEGENERATOR.CORE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CLEANINGSCHEDULEGENERATOR.CORE_LIB
# define CLEANINGSCHEDULEGENERATOR.CORE_EXPORT Q_DECL_EXPORT
#else
# define CLEANINGSCHEDULEGENERATOR.CORE_EXPORT Q_DECL_IMPORT
#endif

#endif // CLEANINGSCHEDULEGENERATOR.CORE_GLOBAL_H
